### ISSUE TITLE
Compilation error even when 'blur' is replaced with 'conv'

### ISSUE THREAD

**Issue by roumenguha** [sammy17/vivado_hls_tutorial#2]
Is there anything else I should be doing? I've tried to address the problem in #1 by renaming the variable, but it doesn't seem to work.

**Comment by roumenguha** [comment]
Nevermind, I was able to get this to compile. I had to change the test image to a smaller one; it seems 1920x1080 is too large to run in csim, but will synthesize just fine.

**Comment by sfuzzy** [comment]
core.cpp -> conv.cpp
blur -> conv
